### ISSUE TITLE
Options not available for Achievements / Boss Fights

### ISSUE THREAD

**Issue by JesperLive** [diomsg-code/Memento#3]
Hi, there are a few things I'd like to report.
I can not seem to find any options for the following things:

Achievements (personal achievements, reached achievement criteria & guild achievements)*
Boss fight (victory & wipe)
For both of these there seem to be no options under the "Achievements / Boss Fights" tabs in the addon settings.

After triggering an event, a delay can be set for creating the screenshot.
Boss killing will be saved and you can choose whether a screenshot should be taken again for a boss that has already been killed
Again, I can not find these settings anywhere.

**Comment by diomsg-code** [comment]
Thanks for the report, but I can't reproduce the problem.
The following should be displayed in the addon options:

![Memento - Options](https://github.com/user-attachments/assets/c0a8422c-efa0-4fa6-99ce-a4c623244502)

Two questions about this:
1. in which WoW version does the problem occur? (Retail, Cata or Classic)
2. can you take a screenshot so that I can see the problem?

**Comment by JesperLive** [comment]
1 Retail
2. 
![image](https://github.com/user-attachments/assets/d15b533b-254a-4d33-b1f8-df45ab6f0e07)

**Comment by diomsg-code** [comment]
I need more information to isolate the problem:
1. what kind of UI framework are you using? ElvUI?
2. are only the options under the first tab not displayed or for all tabs? (e.g. level-up)
3. can you please check whether the display is correct if you deactivate all other add-ons or the UI framework just once?

Thanks

**Comment by diomsg-code** [comment]
If the problem still exists when you have deactivated all other addons, please reset the addon options. (this is possible on the first page of the Memento options page)

**Comment by JesperLive** [comment]
It is indeed ElvUI
The first 3 Tabs have no options under them.
The last 3 all have the tickbox to ether take a screenshot or not, and the delay, that is all.
Disabling all other add-ons works, It appears to conflict with the GoW add-on. When I turn that off, I get all the options.
Unfortunately that add-on is a must have for our Guild.

![image](https://github.com/user-attachments/assets/438df80b-1fb9-4de0-91ae-579569d3d39b)
![image](https://github.com/user-attachments/assets/9df51703-c189-4498-a15d-8f8b895d9704)

I have also reported this there, for your convenience, here is a [link](https://ptb.discord.com/channels/690992060177580084/690992060710387734/1299111531685875856)

**Comment by JesperLive** [comment]
Update, GoW author updated his add-on and fixed it :D

**Comment by diomsg-code** [comment]
Thanks for your feedback. And good luck with collecting achievements and defeating bosses. :)
